### ISSUE TITLE
buy big right angle

### ISSUE THREAD

**Issue by ij0n** [c-base/werc-meta#22]
we need to buy this product: 

https://www.amazon.de/dp/B000ZEG2DU/ref=wl_it_dp_o_pC_nS_ttl?_encoding=UTF8&colid=2SDF14W3XA2FX&coliid=I24G0FARPISZ37

**Comment by berlincount** [comment]
ordered, delivery to my hands expected between 15.-18.10.

**Comment by berlincount** [comment]
confirmed delivery date 20.10., UPS tracking information known to me.

**Comment by berlincount** [comment]
already in my hands

**Comment by ij0n** [comment]
big thx count!
