### ISSUE TITLE
kaufen: schleifscheiben für bandschleifanlage

### ISSUE THREAD

**Issue by ij0n** [c-base/werc-meta#30]
Die eine schleifscheibe die mitgeliefert wurde ist verbraucht. Hier ist eine sinnvolle zusammenstellung von zwei Produkten.dies erachte ich als sinnvollen vorrat dieses verbrauchsgegenstands
- [x] Approved by circle
- [x] bought
- [x] Arrived1
- [x] Arrived2

https://www.amazon.de/gp/aw/d/B01IBK3L56/ref=mp_s_a_1_8?__mk_de_DE=ÅMÅZÕÑ&qid=1476303294&sr=8-8&pi=AC_SX236_SY340_QL65&keywords=schleifscheiben+150+klett&dpPl=1&dpID=51maEPiGdUL&ref=plSrch

Und

https://www.amazon.de/gp/aw/d/B00YS956NA/ref=mp_s_a_1_2?__mk_de_DE=ÅMÅZÕÑ&qid=1476303458&sr=8-2&pi=SY200_QL40&keywords=schleifscheiben+150++klett&dpPl=1&dpID=41iK9F2aRDL&ref=plSrch

**Comment by berlincount** [comment]
erste sind nicht lieferbar, zweitere sind bestellt
