### ISSUE TITLE
Buy new grinding stones for electric bench grinder

### ISSUE THREAD

**Issue by ij0n** [c-base/werc-meta#32]
ID / Bohrung 12,7 mm <  bei Bestellung mit angeben

OD <145 mm nächste standardgröße 125 mm

Fein: https://www.amazon.de/gp/aw/d/B00XKHH7C4/ref=mp_s_a_1_3?__mk_de_DE=ÅMÅZÕÑ&qid=1476385242&sr=8-3&pi=AC_SX236_SY340_FMwebp_QL65&keywords=schleifbock+schleifscheibe+125+12%2C7&dpPl=1&dpID=41a00aE22WL&ref=plSrch#productDescription_secondary_view_div_1476385266617
- [x] Approved by circle
- [x] bought
- [x] Arrived

Grob: https://www.amazon.de/gp/aw/d/B00A3NL5LM/ref=mp_s_a_1_15?__mk_de_DE=ÅMÅZÕÑ&qid=1476385917&sr=8-15&pi=AC_SX236_SY340_FMwebp_QL65&keywords=schleifbockscheibe+125&dpPl=1&dpID=41ULuWuI96L&ref=plSrch

**Comment by berlincount** [comment]
bei bestellung mit angeben versteh ich nicht.

die links sind oberscheisse weil keine web-links und mit query-id drin, welche auch den user identifiziert!

z.B. https://www.amazon.de/gp/product/B00A3NL5LM/ ist weit besser

**Comment by berlincount** [comment]
beide geordert

**Comment by ij0n** [comment]
die feine scheibe ist im arsch. jemand hat die hingerichtet durch unsachgemäße benutzung. 

https://www.amazon.de/St%C3%BCck-NORTON-Schleifscheibe-gr%C3%BCnes-Siliziumkarbid/dp/B00XKHH7C4/

mit 13,6mm einsatz / innendurchmesser.

**Comment by ij0n** [comment]
qshell donated a diamond to repair the damage.
