### ISSUE TITLE
Buy rubber gloves

### ISSUE THREAD

**Issue by ij0n** [c-base/werc-meta#36]
The stockpile from camp15 has been used up.

**Comment by uwekamper** [comment]
http://www.neolab.de/de/shop/arbeitsschutz-reinigung-entsorgung/einmal-handschuhe/neoprotect-nitrilhandschuhe-puderfrei-gr-m-100-stck-pack-1-8102?

**Comment by uwekamper** [comment]
Bei neolab müssten die c-base auch noch eine Kundennummer haben.

**Comment by ij0n** [comment]
has dependency to ticket #4. first we need a bunch of rubber gloves, before we can even think of painting all the panels for weltenbaulab-ceiling

**Comment by ij0n** [comment]
Checked everywhere again. We are really out of rubber gloves and can jzdt buy them at metro.
