### ISSUE TITLE
create two new molds

### ISSUE THREAD

**Issue by ij0n** [c-base/werc-meta#42]
one with some kind of a "beam" shape that can be folded on the knickschmelce ( #25 is a hard dependency and has to be done first). Fold happends in the center and the full size of the mold is 70x70, so after forming and cutting roughly 71.5x71.5cm

another one with a form of roughly 49-50cm by 71,5 for the 45° cornerpieces.

**Comment by cannonerd** [comment]
http://imgur.com/a/DVxzK the beam design.

**Comment by cannonerd** [comment]
http://imgur.com/a/LVhCs the 45 degree design.

**Comment by cannonerd** [comment]
Both designs. http://imgur.com/a/9vxZv

**Comment by ij0n** [comment]
http://imgur.com/a/d8rHa the new beam design. wood is already cut, we decided for a 15° angle

**Comment by ij0n** [comment]
one of the two smaller beams has to be redone or repaired or both. i dont like it.

**Comment by cannonerd** [comment]
The other beam has been repaired. Looks good now.

**Comment by cannonerd** [comment]
The beam mold is completed.

**Comment by ij0n** [comment]
...and it looks glorious!...

**Comment by ij0n** [comment]
Both are fone.
