### ISSUE TITLE
create safety checklist for drillpress

### ISSUE THREAD

**Issue by ij0n** [c-base/werc-meta#48]
we need to create a checklist which will become mandatory to follow for operating the drillpress. the goal is to create something that firstly protects the machine from wrong usage and secondly that protects the user from getting hurt.

**Comment by ij0n** [comment]
random things that need to go on the checklist, but not necessarily in this order.

- use depth stop (no exceptions!)
- use the shield, it has a switch that prevents resetting the emergency-stop when the shield is not deployed
- verify correct height of shield
- check and change if necessary the RPMs
- have coolant ready and know how and when to use it
- use vise for drillpress or use wooden board to drill into (for through-holes). depth stop is mandatory also for through-holes
- verify that the drillpresstable is fixed in rotational position
- verify that the drillpresstable is fixed in vertical position
- reset emergency-stop
- drilling?
- cleanup afterwards

**Comment by ij0n** [comment]
- take off gloves
- secure your hairs, if they are long
- remove rings, bands and other jewelry from your hands and wrists
- reset emergency offswitch
- use centerpunch

**Comment by ij0n** [comment]
add http://www.australianwoodsmith.com.au/pdf/28drillbitspeedchart.pdf to the informations

**Comment by ri0t** [comment]
Reset the drill. That includes:
* remove drill bit
* clean drill bit
* replace drill bit where it belongs (don't create a mess!)
* put back key (the one used to operate the drill head)
* reset table height if you moved it upwards a lot
* remove dust, drilled material, coolant etc from drill and surrounding area

**Comment by ij0n** [comment]
the new drillpress could get a sign "I do not consent to abuse" and the old one could get a sign "rape me instead"

**Comment by uwekamper** [comment]
And in the end it will look like this and nobody will read it:
![](https://c2.staticflickr.com/4/3014/5819059081_97877d23b9_b.jpg)

Which of the rules are really so essential that you will get hurt or damage the equipment when you don't adhere to them. The shorter the list, the more people will read it.

**Comment by ij0n** [comment]
this is not how it works. this is a dangerous machine. you are forbidden to use it, unless you personally got an introduction / instructions how to use it. the checklist is for those that already received the introduction as a little help to really check everything thats necessary. the checklist is not meant for noobs and is not meant to teach someone who has not received the introduction anything.

**Comment by herzmut** [comment]
How about a sign on the workshop door, that the tools inside are not to
be used without a personal instruction?

Am 02.12.2016 um 14:11 schrieb ijon:

**Comment by ij0n** [comment]
#wontfix #securitybyobscurity
